"$schema" = "node_modules/wrangler/config-schema.json"
name = "dontsleep-client"
main = ".output/server/index.mjs"
compatibility_date = "2025-06-25"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".output/public"

[observability]
enabled = true

# D1 Database for download tracking
[[d1_databases]]
binding = "DB"
database_name = "dontsleep-analytics"
database_id = "3e7a33fb-ca7c-48bb-b207-538e0da9af88"

# Production environment (default)
[env.production]
name = "dontsleep-client"

[[env.production.d1_databases]]
binding = "DB"
database_name = "dontsleep-analytics"
database_id = "3e7a33fb-ca7c-48bb-b207-538e0da9af88"
